---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: '🎟️ Add issue tracker to commit message'
description: 'Action to add issue tracker reference to commit message body'

inputs:
  issue_id_lookup_json:
    description: 'JSON mapping/lookup table for issues'
    required: true
  issue_string:
    description: 'String to embed/inject'
    required: false
    default: 'Issue-ID:'
  inject:
    # When injection is enabled and no issue found...
    # String will be added, output variable set true
    description: 'Whether to add an issue tracker if NOT found'
    required: false
    default: 'true'

outputs:
  present:
    description: 'Whether the required Issue tracker is present'
    value: ${{ steps.status.outputs.present }}

runs:
  using: 'composite'
  steps:
    - name: 'Get GIT commit message body'
      id: commit-message
      # yamllint disable rule:line-length
      uses: lfreleng-actions/git-commit-message-action@4a5b845bd35d9363a8ab59824d374d1b2967666e # v0.1.1

    - name: 'Check commit message for issue tracker reference'
      shell: bash
      env:
        STEP_COMMIT_MESSAGE: ${{ steps.commit-message.outputs.commit_message }}
        INPUT_ISSUE_STRING: ${{ inputs.issue_string }}
      run: |
        # Check commit message for issue tracker reference
        echo "# Checking Commit Message for Issue Tracker" >> "$GITHUB_STEP_SUMMARY"

        COMMIT_MESSAGE="$STEP_COMMIT_MESSAGE"
        if [ -z "$COMMIT_MESSAGE" ]; then
          echo 'Commit message body was empty/unpopulated ❌'; exit 1
        fi
        if [[ "$COMMIT_MESSAGE" =~ "$INPUT_ISSUE_STRING" ]]; then
          echo 'Issue tracker found in pull request ✅' >> "$GITHUB_STEP_SUMMARY"
          echo 'Issue tracker found in pull request ✅'
          echo 'PRESENT=true' >> "$GITHUB_ENV"
        else
          echo 'Issue tracker NOT found in pull request ❌' >> "$GITHUB_STEP_SUMMARY"
          echo 'Issue tracker NOT found in pull request ❌'
          echo 'PRESENT=false' >> "$GITHUB_ENV"
        fi

    - name: 'Set key to use for JSON lookup'
      id: set-key
      if: env.PRESENT == 'false' && inputs.inject == 'true'
      shell: bash
      env:
        GH_ACTOR: ${{ github.actor }}
        GH_ACTOR_ID: ${{ github.actor_id }}
      run: |
        # Set key to use for JSON lookup
        ACTOR="$GH_ACTOR"
        ACTOR_ID="$GH_ACTOR_ID"
        echo "Using GitHub actor as lookup key: $ACTOR [$ACTOR_ID] 🔑"
        echo "key=$ACTOR" >> "$GITHUB_OUTPUT"

    - name: 'Get ticket from JSON lookup table'
      id: lookup
      if: env.PRESENT == 'false' && inputs.inject == 'true'
      uses: lfreleng-actions/json-key-value-lookup-action@6622b1017699e557a76c8d041cfb7378160424c9 # v0.1.2
      with:
        json: ${{ inputs.issue_id_lookup_json }}
        key: ${{ steps.set-key.outputs.key }}

    - name: 'Configure GIT user for commit'
      if: env.PRESENT == 'false' && inputs.inject == 'true'
      uses: lfreleng-actions/git-configure-action@38baf145299bef616b58a99123971a1da3bf8ab6 # v0.1.1

    - name: 'Adding issue tracker to commit message'
      id: inject
      # yamllint disable-line rule:line-length
      if: env.PRESENT == 'false' && inputs.inject == 'true' && (github.event.pull_request.head.ref != github.ref_name) && (github.event.pull_request.head.ref != github.event.pull_request.base.ref)
      shell: bash
      env:
        INPUT_ISSUE_STRING: ${{ inputs.issue_string }}
        STEP_VALUE: ${{ steps.lookup.outputs.value }}
      run: |
        # Adding issue tracker reference to commit message
        git commit --amend --trailer "$INPUT_ISSUE_STRING $STEP_VALUE" --no-verify --no-edit
        echo "Performing force push on pull request ⚠️"
        git push --force
        echo "present=true" >> "$GITHUB_ENV"
        echo "Added issue tracker reference: $STEP_VALUE 🎟️"
        echo "### 🎟️ Added issue tracker reference: $STEP_VALUE" >> "$GITHUB_STEP_SUMMARY"

    - name: 'Set status/outputs'
      id: status
      shell: bash
      env:
        ENV_PRESENT_LOWER: ${{ env.present }}
        ENV_PRESENT_UPPER: ${{ env.PRESENT }}
      run: |
        # Set status/outputs
        if [ -n "$ENV_PRESENT_LOWER" ]; then
          echo "present=$ENV_PRESENT_LOWER" >> "$GITHUB_OUTPUT"
        else
          echo "present=$ENV_PRESENT_UPPER" >> "$GITHUB_OUTPUT"
        fi
